import bpy


from mathutils import Color


def create(obj):
    # generated by gamerig.utils.write_metarig

    obj.rotation_mode     = 'XYZ'
    obj.rotation_euler      = (0.0, 0.0, 0.0)
    obj.rotation_quaternion = (1.0, 0.0, 0.0, 0.0)
    obj.rotation_axis_angle = (0.0, 0.0, 1.0, 0.0)

    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    arm.gamerig.rig_ui_template = 'ui_template'

    for i in range(6):
        arm.gamerig.colors.add()

    arm.gamerig.colors[0].name = "Root"
    arm.gamerig.colors[0].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[0].normal = Color((0.4352940022945404, 0.18431399762630463, 0.4156860113143921))
    arm.gamerig.colors[0].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[0].standard_colors_lock = True
    arm.gamerig.colors[1].name = "IK"
    arm.gamerig.colors[1].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[1].normal = Color((0.6039220094680786, 0.0, 0.0))
    arm.gamerig.colors[1].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[1].standard_colors_lock = True
    arm.gamerig.colors[2].name = "Special"
    arm.gamerig.colors[2].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[2].normal = Color((0.9568629860877991, 0.7882350087165833, 0.04705899953842163))
    arm.gamerig.colors[2].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[2].standard_colors_lock = True
    arm.gamerig.colors[3].name = "Tweak"
    arm.gamerig.colors[3].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[3].normal = Color((0.03921600058674812, 0.21176500618457794, 0.5803920030593872))
    arm.gamerig.colors[3].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[3].standard_colors_lock = True
    arm.gamerig.colors[4].name = "FK"
    arm.gamerig.colors[4].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[4].normal = Color((0.11764699965715408, 0.5686269998550415, 0.035294000059366226))
    arm.gamerig.colors[4].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[4].standard_colors_lock = True
    arm.gamerig.colors[5].name = "Extra"
    arm.gamerig.colors[5].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[5].normal = Color((0.9686279892921448, 0.2509799897670746, 0.09411799907684326))
    arm.gamerig.colors[5].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[5].standard_colors_lock = True

    if len(arm.collections) > 0:
        for i in arm.collections:
            arm.collections.remove(i)
    arm.collections.new("Face")
    arm.collections[-1].gamerig.row = 1
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Face (Primary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Face (Secondary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Torso")
    arm.collections[-1].gamerig.row = 3
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Torso (Tweak)")
    arm.collections[-1].gamerig.row = 4
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Fingers.L")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Fingers.R")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Arm.L (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.L (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Arm.R (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.R (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.L (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.L (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.R (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.R (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Root")
    arm.collections[-1].gamerig.row = 14
    arm.collections[-1].gamerig.group = 1

    bones = {}

    bone = arm.edit_bones.new('root')
    bone.head[:] = -0.0000, 0.0000, 0.0000
    bone.tail[:] = 0.5000, 0.0000, 0.0000
    bone.roll = 1.5708
    bone.use_connect = False
    bone.use_deform = True
    bones['root'] = bone.name
    bone = arm.edit_bones.new('pelvis')
    bone.head[:] = -0.0000, 0.0106, 0.9675
    bone.tail[:] = -0.0000, 0.0017, 1.0756
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['root']]
    bones['pelvis'] = bone.name
    bone = arm.edit_bones.new('spine_01')
    bone.head[:] = -0.0000, 0.0017, 1.0756
    bone.tail[:] = -0.0000, 0.0152, 1.2676
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pelvis']]
    bones['spine_01'] = bone.name
    bone = arm.edit_bones.new('thigh_r')
    bone.head[:] = -0.0901, 0.0053, 0.9530
    bone.tail[:] = -0.1422, 0.0180, 0.5307
    bone.roll = 0.2686
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pelvis']]
    bones['thigh_r'] = bone.name
    bone = arm.edit_bones.new('thigh_l')
    bone.head[:] = 0.0901, 0.0053, 0.9530
    bone.tail[:] = 0.1422, 0.0180, 0.5307
    bone.roll = -0.2686
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pelvis']]
    bones['thigh_l'] = bone.name
    bone = arm.edit_bones.new('spine_02')
    bone.head[:] = -0.0000, 0.0152, 1.2676
    bone.tail[:] = -0.0000, 0.0350, 1.4003
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['spine_01']]
    bones['spine_02'] = bone.name
    bone = arm.edit_bones.new('calf_r')
    bone.head[:] = -0.1422, 0.0180, 0.5307
    bone.tail[:] = -0.1708, 0.0807, 0.1347
    bone.roll = 0.1245
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh_r']]
    bones['calf_r'] = bone.name
    bone = arm.edit_bones.new('thigh_twist_01_r')
    bone.head[:] = -0.1171, 0.0119, 0.7338
    bone.tail[:] = -0.1422, 0.0182, 0.5303
    bone.roll = 0.1735
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh_r']]
    bones['thigh_twist_01_r'] = bone.name
    bone = arm.edit_bones.new('calf_l')
    bone.head[:] = 0.1422, 0.0180, 0.5307
    bone.tail[:] = 0.1708, 0.0807, 0.1347
    bone.roll = -0.1246
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh_l']]
    bones['calf_l'] = bone.name
    bone = arm.edit_bones.new('thigh_twist_01_l')
    bone.head[:] = 0.1171, 0.0119, 0.7338
    bone.tail[:] = 0.1422, 0.0182, 0.5303
    bone.roll = -0.1735
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh_l']]
    bones['thigh_twist_01_l'] = bone.name
    bone = arm.edit_bones.new('spine_03')
    bone.head[:] = -0.0000, 0.0350, 1.4003
    bone.tail[:] = -0.0000, 0.0587, 1.5642
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['spine_02']]
    bones['spine_03'] = bone.name
    bone = arm.edit_bones.new('calf_twist_01_r')
    bone.head[:] = -0.1567, 0.0500, 0.3289
    bone.tail[:] = -0.1715, 0.0842, 0.1323
    bone.roll = 0.1327
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['calf_r']]
    bones['calf_twist_01_r'] = bone.name
    bone = arm.edit_bones.new('foot_r')
    bone.head[:] = -0.1708, 0.0807, 0.1347
    bone.tail[:] = -0.1791, -0.0836, 0.0281
    bone.roll = 0.0604
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['calf_r']]
    bones['foot_r'] = bone.name
    bone = arm.edit_bones.new('calf_twist_01_l')
    bone.head[:] = 0.1567, 0.0500, 0.3289
    bone.tail[:] = 0.1715, 0.0842, 0.1323
    bone.roll = -0.1327
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['calf_l']]
    bones['calf_twist_01_l'] = bone.name
    bone = arm.edit_bones.new('foot_l')
    bone.head[:] = 0.1708, 0.0807, 0.1347
    bone.tail[:] = 0.1791, -0.0836, 0.0281
    bone.roll = -0.0604
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['calf_l']]
    bones['foot_l'] = bone.name
    bone = arm.edit_bones.new('clavicle_l')
    bone.head[:] = 0.0378, 0.0276, 1.5220
    bone.tail[:] = 0.1770, 0.0971, 1.4953
    bone.roll = 1.6761
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['spine_03']]
    bones['clavicle_l'] = bone.name
    bone = arm.edit_bones.new('neck_01')
    bone.head[:] = -0.0000, 0.0587, 1.5642
    bone.tail[:] = 0.0000, 0.0398, 1.6552
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['spine_03']]
    bones['neck_01'] = bone.name
    bone = arm.edit_bones.new('clavicle_r')
    bone.head[:] = -0.0378, 0.0276, 1.5220
    bone.tail[:] = -0.1770, 0.0971, 1.4953
    bone.roll = -1.6761
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['spine_03']]
    bones['clavicle_r'] = bone.name
    bone = arm.edit_bones.new('JIG-heel_r')
    bone.head[:] = -0.1411, 0.1162, 0.0000
    bone.tail[:] = -0.2137, 0.1162, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot_r']]
    bones['JIG-heel_r'] = bone.name
    bone = arm.edit_bones.new('ball_r')
    bone.head[:] = -0.1791, -0.0836, 0.0281
    bone.tail[:] = -0.1822, -0.1496, 0.0251
    bone.roll = 1.5856
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot_r']]
    bones['ball_r'] = bone.name
    bone = arm.edit_bones.new('ball_l')
    bone.head[:] = 0.1791, -0.0836, 0.0281
    bone.tail[:] = 0.1822, -0.1496, 0.0251
    bone.roll = -1.5857
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot_l']]
    bones['ball_l'] = bone.name
    bone = arm.edit_bones.new('JIG-heel_l')
    bone.head[:] = 0.1411, 0.1162, 0.0000
    bone.tail[:] = 0.2137, 0.1162, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot_l']]
    bones['JIG-heel_l'] = bone.name
    bone = arm.edit_bones.new('upperarm_l')
    bone.head[:] = 0.1770, 0.0971, 1.4953
    bone.tail[:] = 0.3726, 0.1191, 1.2645
    bone.roll = 2.4108
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['clavicle_l']]
    bones['upperarm_l'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head[:] = 0.0000, 0.0398, 1.6552
    bone.tail[:] = 0.0000, 0.0435, 1.8150
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['neck_01']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('upperarm_r')
    bone.head[:] = -0.1770, 0.0971, 1.4953
    bone.tail[:] = -0.3726, 0.1191, 1.2645
    bone.roll = -2.4108
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['clavicle_r']]
    bones['upperarm_r'] = bone.name
    bone = arm.edit_bones.new('lowerarm_l')
    bone.head[:] = 0.3726, 0.1191, 1.2645
    bone.tail[:] = 0.5665, 0.0034, 1.1168
    bone.roll = 2.0401
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upperarm_l']]
    bones['lowerarm_l'] = bone.name
    bone = arm.edit_bones.new('upperarm_twist_01_l')
    bone.head[:] = 0.1802, 0.0975, 1.4915
    bone.tail[:] = 0.2797, 0.1087, 1.3742
    bone.roll = 2.4108
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upperarm_l']]
    bones['upperarm_twist_01_l'] = bone.name
    bone = arm.edit_bones.new('lowerarm_r')
    bone.head[:] = -0.3726, 0.1191, 1.2645
    bone.tail[:] = -0.5665, 0.0034, 1.1168
    bone.roll = -2.0401
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upperarm_r']]
    bones['lowerarm_r'] = bone.name
    bone = arm.edit_bones.new('upperarm_twist_01_r')
    bone.head[:] = -0.1802, 0.0975, 1.4915
    bone.tail[:] = -0.2797, 0.1087, 1.3742
    bone.roll = -2.4108
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upperarm_r']]
    bones['upperarm_twist_01_r'] = bone.name
    bone = arm.edit_bones.new('hand_l')
    bone.head[:] = 0.5665, 0.0034, 1.1168
    bone.tail[:] = 0.6406, -0.0444, 1.0546
    bone.roll = 0.7742
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['lowerarm_l']]
    bones['hand_l'] = bone.name
    bone = arm.edit_bones.new('lowerarm_twist_01_l')
    bone.head[:] = 0.4732, 0.0590, 1.1878
    bone.tail[:] = 0.5660, 0.0036, 1.1172
    bone.roll = 2.0401
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['lowerarm_l']]
    bones['lowerarm_twist_01_l'] = bone.name
    bone = arm.edit_bones.new('hand_r')
    bone.head[:] = -0.5665, 0.0034, 1.1168
    bone.tail[:] = -0.6406, -0.0444, 1.0546
    bone.roll = -0.7742
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['lowerarm_r']]
    bones['hand_r'] = bone.name
    bone = arm.edit_bones.new('lowerarm_twist_01_r')
    bone.head[:] = -0.4732, 0.0590, 1.1878
    bone.tail[:] = -0.5660, 0.0036, 1.1172
    bone.roll = -2.0401
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['lowerarm_r']]
    bones['lowerarm_twist_01_r'] = bone.name
    bone = arm.edit_bones.new('index_01_l')
    bone.head[:] = 0.6304, -0.0677, 1.0381
    bone.tail[:] = 0.6467, -0.0809, 1.0008
    bone.roll = 1.6880
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_l']]
    bones['index_01_l'] = bone.name
    bone = arm.edit_bones.new('middle_01_l')
    bone.head[:] = 0.6449, -0.0448, 1.0348
    bone.tail[:] = 0.6653, -0.0572, 0.9950
    bone.roll = 1.3766
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_l']]
    bones['middle_01_l'] = bone.name
    bone = arm.edit_bones.new('pinky_01_l')
    bone.head[:] = 0.6403, 0.0016, 1.0302
    bone.tail[:] = 0.6594, -0.0013, 1.0002
    bone.roll = 0.8965
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_l']]
    bones['pinky_01_l'] = bone.name
    bone = arm.edit_bones.new('ring_01_l')
    bone.head[:] = 0.6458, -0.0208, 1.0304
    bone.tail[:] = 0.6659, -0.0298, 0.9920
    bone.roll = 1.0972
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_l']]
    bones['ring_01_l'] = bone.name
    bone = arm.edit_bones.new('thumb_01_l')
    bone.head[:] = 0.5748, -0.0388, 1.0764
    bone.tail[:] = 0.5761, -0.0708, 1.0547
    bone.roll = -2.6270
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_l']]
    bones['thumb_01_l'] = bone.name
    bone = arm.edit_bones.new('index_01_r')
    bone.head[:] = -0.6304, -0.0677, 1.0381
    bone.tail[:] = -0.6467, -0.0809, 1.0008
    bone.roll = -1.6880
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_r']]
    bones['index_01_r'] = bone.name
    bone = arm.edit_bones.new('middle_01_r')
    bone.head[:] = -0.6449, -0.0448, 1.0348
    bone.tail[:] = -0.6653, -0.0572, 0.9950
    bone.roll = -1.3766
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_r']]
    bones['middle_01_r'] = bone.name
    bone = arm.edit_bones.new('pinky_01_r')
    bone.head[:] = -0.6403, 0.0016, 1.0302
    bone.tail[:] = -0.6594, -0.0013, 1.0002
    bone.roll = -0.8965
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_r']]
    bones['pinky_01_r'] = bone.name
    bone = arm.edit_bones.new('ring_01_r')
    bone.head[:] = -0.6458, -0.0208, 1.0304
    bone.tail[:] = -0.6659, -0.0298, 0.9920
    bone.roll = -1.0972
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_r']]
    bones['ring_01_r'] = bone.name
    bone = arm.edit_bones.new('thumb_01_r')
    bone.head[:] = -0.5748, -0.0388, 1.0764
    bone.tail[:] = -0.5761, -0.0708, 1.0547
    bone.roll = 2.6270
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand_r']]
    bones['thumb_01_r'] = bone.name
    bone = arm.edit_bones.new('index_02_l')
    bone.head[:] = 0.6467, -0.0809, 1.0008
    bone.tail[:] = 0.6544, -0.0876, 0.9684
    bone.roll = 1.9376
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['index_01_l']]
    bones['index_02_l'] = bone.name
    bone = arm.edit_bones.new('middle_02_l')
    bone.head[:] = 0.6653, -0.0572, 0.9950
    bone.tail[:] = 0.6743, -0.0654, 0.9607
    bone.roll = 1.6098
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['middle_01_l']]
    bones['middle_02_l'] = bone.name
    bone = arm.edit_bones.new('pinky_02_l')
    bone.head[:] = 0.6594, -0.0013, 1.0002
    bone.tail[:] = 0.6701, -0.0035, 0.9724
    bone.roll = 1.1304
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pinky_01_l']]
    bones['pinky_02_l'] = bone.name
    bone = arm.edit_bones.new('ring_02_l')
    bone.head[:] = 0.6659, -0.0298, 0.9920
    bone.tail[:] = 0.6743, -0.0355, 0.9587
    bone.roll = 1.3845
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['ring_01_l']]
    bones['ring_02_l'] = bone.name
    bone = arm.edit_bones.new('thumb_02_l')
    bone.head[:] = 0.5761, -0.0708, 1.0547
    bone.tail[:] = 0.5778, -0.0957, 1.0226
    bone.roll = -2.6140
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb_01_l']]
    bones['thumb_02_l'] = bone.name
    bone = arm.edit_bones.new('index_02_r')
    bone.head[:] = -0.6467, -0.0809, 1.0008
    bone.tail[:] = -0.6544, -0.0876, 0.9684
    bone.roll = -1.9376
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['index_01_r']]
    bones['index_02_r'] = bone.name
    bone = arm.edit_bones.new('middle_02_r')
    bone.head[:] = -0.6653, -0.0572, 0.9950
    bone.tail[:] = -0.6743, -0.0654, 0.9607
    bone.roll = -1.6098
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['middle_01_r']]
    bones['middle_02_r'] = bone.name
    bone = arm.edit_bones.new('pinky_02_r')
    bone.head[:] = -0.6594, -0.0013, 1.0002
    bone.tail[:] = -0.6701, -0.0035, 0.9724
    bone.roll = -1.1304
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pinky_01_r']]
    bones['pinky_02_r'] = bone.name
    bone = arm.edit_bones.new('ring_02_r')
    bone.head[:] = -0.6659, -0.0298, 0.9920
    bone.tail[:] = -0.6743, -0.0355, 0.9587
    bone.roll = -1.3845
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['ring_01_r']]
    bones['ring_02_r'] = bone.name
    bone = arm.edit_bones.new('thumb_02_r')
    bone.head[:] = -0.5761, -0.0708, 1.0547
    bone.tail[:] = -0.5778, -0.0957, 1.0226
    bone.roll = 2.6140
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb_01_r']]
    bones['thumb_02_r'] = bone.name
    bone = arm.edit_bones.new('index_03_l')
    bone.head[:] = 0.6544, -0.0876, 0.9684
    bone.tail[:] = 0.6639, -0.0960, 0.9435
    bone.roll = 1.7929
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['index_02_l']]
    bones['index_03_l'] = bone.name
    bone = arm.edit_bones.new('middle_03_l')
    bone.head[:] = 0.6743, -0.0654, 0.9607
    bone.tail[:] = 0.6902, -0.0723, 0.9343
    bone.roll = 1.2628
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['middle_02_l']]
    bones['middle_03_l'] = bone.name
    bone = arm.edit_bones.new('pinky_03_l')
    bone.head[:] = 0.6701, -0.0035, 0.9724
    bone.tail[:] = 0.6782, -0.0069, 0.9508
    bone.roll = 1.1524
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pinky_02_l']]
    bones['pinky_03_l'] = bone.name
    bone = arm.edit_bones.new('ring_03_l')
    bone.head[:] = 0.6743, -0.0355, 0.9587
    bone.tail[:] = 0.6870, -0.0419, 0.9340
    bone.roll = 1.1124
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['ring_02_l']]
    bones['ring_03_l'] = bone.name
    bone = arm.edit_bones.new('thumb_03_l')
    bone.head[:] = 0.5778, -0.0957, 1.0226
    bone.tail[:] = 0.5749, -0.1204, 1.0000
    bone.roll = -2.2586
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb_02_l']]
    bones['thumb_03_l'] = bone.name
    bone = arm.edit_bones.new('index_03_r')
    bone.head[:] = -0.6544, -0.0876, 0.9684
    bone.tail[:] = -0.6639, -0.0960, 0.9435
    bone.roll = -1.7929
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['index_02_r']]
    bones['index_03_r'] = bone.name
    bone = arm.edit_bones.new('middle_03_r')
    bone.head[:] = -0.6743, -0.0654, 0.9607
    bone.tail[:] = -0.6902, -0.0723, 0.9343
    bone.roll = -1.2628
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['middle_02_r']]
    bones['middle_03_r'] = bone.name
    bone = arm.edit_bones.new('pinky_03_r')
    bone.head[:] = -0.6701, -0.0035, 0.9724
    bone.tail[:] = -0.6782, -0.0069, 0.9508
    bone.roll = -1.1524
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['pinky_02_r']]
    bones['pinky_03_r'] = bone.name
    bone = arm.edit_bones.new('ring_03_r')
    bone.head[:] = -0.6743, -0.0355, 0.9587
    bone.tail[:] = -0.6870, -0.0419, 0.9340
    bone.roll = -1.1124
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['ring_02_r']]
    bones['ring_03_r'] = bone.name
    bone = arm.edit_bones.new('thumb_03_r')
    bone.head[:] = -0.5778, -0.0957, 1.0226
    bone.tail[:] = -0.5749, -0.1204, 1.0000
    bone.roll = 2.2586
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb_02_r']]
    bones['thumb_03_r'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['root']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Root'].assign(pbone)
    try:
        pbone.gamerig.name = "root"
    except AttributeError:
        pass
    try:
        pbone.gamerig.widget_plane = "yz"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['pelvis']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "torso"
    except AttributeError:
        pass
    try:
        pbone.gamerig.tweak_bone_collection = "Torso (Tweak)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine_01']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['thigh_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.footprint_bone = "JIG-heel_r"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.R (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.footprint_bone = "JIG-heel_l"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.L (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine_02']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['calf_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['thigh_twist_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['calf_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['thigh_twist_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['spine_03']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['calf_twist_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['foot_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['calf_twist_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['foot_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['clavicle_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "generic"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['neck_01']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['clavicle_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "generic"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['JIG-heel_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['ball_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['ball_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['upperarm_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.L (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Face'].assign(pbone)
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['upperarm_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.R (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['lowerarm_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['upperarm_twist_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['lowerarm_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['upperarm_twist_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['hand_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['lowerarm_twist_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['hand_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['lowerarm_twist_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['index_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['middle_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['pinky_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ring_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb_01_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "thumb"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['index_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['middle_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['pinky_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ring_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb_01_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "thumb"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['index_02_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['middle_02_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['pinky_02_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['ring_02_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb_02_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['index_02_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['middle_02_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['pinky_02_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['ring_02_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb_02_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['index_03_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['middle_03_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['pinky_03_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['ring_03_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb_03_l']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['index_03_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['middle_03_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['pinky_03_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['ring_03_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb_03_r']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

if __name__ == "__main__":
    create(bpy.context.active_object)
