import bpy


from mathutils import Color


def create(obj):
    # generated by gamerig.utils.write_metarig

    obj.rotation_mode     = 'XYZ'
    obj.rotation_euler      = (1.5707963705062866, 0.0, 0.0)
    obj.rotation_quaternion = (1.0, 0.0, 0.0, 0.0)
    obj.rotation_axis_angle = (0.0, 0.0, 1.0, 0.0)

    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    arm.gamerig.rig_ui_template = 'ui_template'

    for i in range(6):
        arm.gamerig.colors.add()

    arm.gamerig.colors[0].name = "Root"
    arm.gamerig.colors[0].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[0].normal = Color((0.67384934425354, 0.09994713962078094, 0.605361819267273))
    arm.gamerig.colors[0].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[0].standard_colors_lock = True
    arm.gamerig.colors[1].name = "FK"
    arm.gamerig.colors[1].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[1].normal = Color((0.2890395522117615, 1.0, 0.08723420649766922))
    arm.gamerig.colors[1].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[1].standard_colors_lock = True
    arm.gamerig.colors[2].name = "IK"
    arm.gamerig.colors[2].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[2].normal = Color((0.9568628668785095, 0.21056735515594482, 0.234207421541214))
    arm.gamerig.colors[2].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[2].standard_colors_lock = True
    arm.gamerig.colors[3].name = "Tweak"
    arm.gamerig.colors[3].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[3].normal = Color((0.03921600058674812, 0.21176500618457794, 0.5803920030593872))
    arm.gamerig.colors[3].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[3].standard_colors_lock = True
    arm.gamerig.colors[4].name = "Special"
    arm.gamerig.colors[4].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[4].normal = Color((0.7191200852394104, 0.7356600761413574, 0.011989133432507515))
    arm.gamerig.colors[4].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[4].standard_colors_lock = True
    arm.gamerig.colors[5].name = "Extra"
    arm.gamerig.colors[5].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[5].normal = Color((0.09200122952461243, 0.041189342737197876, 0.9686281681060791))
    arm.gamerig.colors[5].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[5].standard_colors_lock = True

    if len(arm.collections) > 0:
        for i in arm.collections:
            arm.collections.remove(i)
    arm.collections.new("Face")
    arm.collections[-1].gamerig.row = 1
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Face (Primary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Face (Secondary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Torso")
    arm.collections[-1].gamerig.row = 3
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Torso (Tweak)")
    arm.collections[-1].gamerig.row = 4
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Fingers.L")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Fingers.r")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Arm.L (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.L (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Arm.R (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.R (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.L (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.L (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.R (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.R (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Root")
    arm.collections[-1].gamerig.row = 14
    arm.collections[-1].gamerig.group = 1

    bones = {}

    bone = arm.edit_bones.new('hips')
    bone.head[:] = 0.0000, 0.9062, -0.0433
    bone.tail[:] = 0.0000, 1.0727, 0.0035
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bones['hips'] = bone.name
    bone = arm.edit_bones.new('waist')
    bone.head[:] = 0.0000, 1.0727, 0.0035
    bone.tail[:] = 0.0000, 1.1916, 0.0103
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['waist'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head[:] = 0.0877, 0.9470, 0.0039
    bone.tail[:] = 0.0880, 0.4738, 0.0310
    bone.roll = 0.0228
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head[:] = -0.0877, 0.9470, 0.0039
    bone.tail[:] = -0.0880, 0.4738, 0.0310
    bone.roll = -0.0228
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('chest')
    bone.head[:] = 0.0000, 1.1916, 0.0103
    bone.tail[:] = 0.0000, 1.3049, 0.0071
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['waist']]
    bones['chest'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head[:] = 0.0880, 0.4738, 0.0310
    bone.tail[:] = 0.0883, 0.0747, -0.0145
    bone.roll = -0.0125
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head[:] = -0.0880, 0.4738, 0.0310
    bone.tail[:] = -0.0883, 0.0747, -0.0145
    bone.roll = 0.0125
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('upper_chest')
    bone.head[:] = 0.0000, 1.3049, 0.0071
    bone.tail[:] = 0.0000, 1.4716, -0.0102
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['chest']]
    bones['upper_chest'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head[:] = 0.0883, 0.0747, -0.0145
    bone.tail[:] = 0.0890, 0.0148, 0.0836
    bone.roll = 0.0325
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head[:] = -0.0883, 0.0747, -0.0145
    bone.tail[:] = -0.0890, 0.0148, 0.0836
    bone.roll = -0.0325
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('shoulder.L')
    bone.head[:] = 0.0216, 1.4241, 0.0141
    bone.tail[:] = 0.1516, 1.4240, -0.0183
    bone.roll = -1.3267
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_chest']]
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('shoulder.R')
    bone.head[:] = -0.0216, 1.4241, 0.0141
    bone.tail[:] = -0.1516, 1.4240, -0.0183
    bone.roll = 1.3267
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_chest']]
    bones['shoulder.R'] = bone.name
    bone = arm.edit_bones.new('neck')
    bone.head[:] = 0.0000, 1.4716, -0.0102
    bone.tail[:] = 0.0000, 1.5619, -0.0015
    bone.roll = -0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_chest']]
    bones['neck'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head[:] = 0.0890, 0.0148, 0.0836
    bone.tail[:] = 0.0890, 0.0143, 0.1437
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('JIG-heel.L')
    bone.head[:] = 0.0551, -0.0000, -0.0411
    bone.tail[:] = 0.1267, -0.0000, -0.0411
    bone.roll = -1.5708
    bone.use_connect = False
    bone.use_deform = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['JIG-heel.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head[:] = -0.0890, 0.0148, 0.0836
    bone.tail[:] = -0.0890, 0.0143, 0.1437
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('JIG-heel.R')
    bone.head[:] = -0.0551, -0.0000, -0.0411
    bone.tail[:] = -0.1267, -0.0000, -0.0411
    bone.roll = 1.5708
    bone.use_connect = False
    bone.use_deform = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['JIG-heel.R'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head[:] = 0.1748, 1.4057, -0.0239
    bone.tail[:] = 0.4329, 1.4017, -0.0465
    bone.roll = 0.0256
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head[:] = -0.1748, 1.4057, -0.0239
    bone.tail[:] = -0.4329, 1.4017, -0.0465
    bone.roll = -0.0256
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shoulder.R']]
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head[:] = 0.0000, 1.5619, -0.0015
    bone.tail[:] = 0.0000, 1.7394, -0.0015
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['neck']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head[:] = 0.4329, 1.4017, -0.0465
    bone.tail[:] = 0.6681, 1.3980, -0.0144
    bone.roll = -0.2011
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head[:] = -0.4329, 1.4017, -0.0465
    bone.tail[:] = -0.6681, 1.3980, -0.0144
    bone.roll = 0.2011
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('eye.L')
    bone.head[:] = 0.0462, 1.6629, 0.0721
    bone.tail[:] = 0.0462, 1.6629, 0.0938
    bone.roll = 3.1416
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.L'] = bone.name
    bone = arm.edit_bones.new('eye.R')
    bone.head[:] = -0.0462, 1.6629, 0.0721
    bone.tail[:] = -0.0462, 1.6629, 0.0938
    bone.roll = 3.1416
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.R'] = bone.name
    bone = arm.edit_bones.new('jaw')
    bone.head[:] = 0.0000, 1.6055, -0.0018
    bone.tail[:] = 0.0000, 1.5663, 0.0828
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['head']]
    bones['jaw'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head[:] = 0.6681, 1.3980, -0.0144
    bone.tail[:] = 0.7398, 1.3968, -0.0147
    bone.roll = 1.5803
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('hand.R')
    bone.head[:] = -0.6681, 1.3980, -0.0144
    bone.tail[:] = -0.7398, 1.3968, -0.0147
    bone.roll = -1.5803
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['hand.R'] = bone.name
    bone = arm.edit_bones.new('f_index.01.L')
    bone.head[:] = 0.7529, 1.4114, 0.0177
    bone.tail[:] = 0.7925, 1.3988, 0.0197
    bone.roll = 1.8244
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_index.01.L'] = bone.name
    bone = arm.edit_bones.new('thumb.01.L')
    bone.head[:] = 0.6881, 1.3838, 0.0128
    bone.tail[:] = 0.7261, 1.3695, 0.0296
    bone.roll = 2.7126
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['thumb.01.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.L')
    bone.head[:] = 0.7559, 1.4143, -0.0028
    bone.tail[:] = 0.7962, 1.3972, -0.0006
    bone.roll = 1.6187
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_middle.01.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.L')
    bone.head[:] = 0.7559, 1.4140, -0.0247
    bone.tail[:] = 0.7937, 1.3939, -0.0240
    bone.roll = 1.5735
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_ring.01.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.L')
    bone.head[:] = 0.7547, 1.4115, -0.0463
    bone.tail[:] = 0.7799, 1.3976, -0.0473
    bone.roll = 1.3256
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_pinky.01.L'] = bone.name
    bone = arm.edit_bones.new('f_index.01.R')
    bone.head[:] = -0.7529, 1.4114, 0.0177
    bone.tail[:] = -0.7925, 1.3988, 0.0197
    bone.roll = -1.8244
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_index.01.R'] = bone.name
    bone = arm.edit_bones.new('thumb.01.R')
    bone.head[:] = -0.6881, 1.3838, 0.0128
    bone.tail[:] = -0.7261, 1.3695, 0.0296
    bone.roll = -2.7126
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['thumb.01.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.R')
    bone.head[:] = -0.7559, 1.4143, -0.0028
    bone.tail[:] = -0.7962, 1.3972, -0.0006
    bone.roll = -1.6187
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_middle.01.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.R')
    bone.head[:] = -0.7559, 1.4140, -0.0247
    bone.tail[:] = -0.7937, 1.3939, -0.0240
    bone.roll = -1.5735
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_ring.01.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.R')
    bone.head[:] = -0.7547, 1.4115, -0.0463
    bone.tail[:] = -0.7799, 1.3976, -0.0473
    bone.roll = -1.3256
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_pinky.01.R'] = bone.name
    bone = arm.edit_bones.new('f_index.02.L')
    bone.head[:] = 0.7925, 1.3988, 0.0197
    bone.tail[:] = 0.8140, 1.3881, 0.0199
    bone.roll = 1.7286
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.01.L']]
    bones['f_index.02.L'] = bone.name
    bone = arm.edit_bones.new('thumb.02.L')
    bone.head[:] = 0.7261, 1.3695, 0.0296
    bone.tail[:] = 0.7475, 1.3623, 0.0344
    bone.roll = 3.0798
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.01.L']]
    bones['thumb.02.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.L')
    bone.head[:] = 0.7962, 1.3972, -0.0006
    bone.tail[:] = 0.8176, 1.3827, -0.0003
    bone.roll = 1.5726
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.01.L']]
    bones['f_middle.02.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.L')
    bone.head[:] = 0.7937, 1.3939, -0.0240
    bone.tail[:] = 0.8112, 1.3799, -0.0242
    bone.roll = 1.5880
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.01.L']]
    bones['f_ring.02.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.L')
    bone.head[:] = 0.7799, 1.3976, -0.0473
    bone.tail[:] = 0.7922, 1.3862, -0.0480
    bone.roll = 1.4181
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.L']]
    bones['f_pinky.02.L'] = bone.name
    bone = arm.edit_bones.new('f_index.02.R')
    bone.head[:] = -0.7925, 1.3988, 0.0197
    bone.tail[:] = -0.8140, 1.3881, 0.0199
    bone.roll = -1.7286
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.01.R']]
    bones['f_index.02.R'] = bone.name
    bone = arm.edit_bones.new('thumb.02.R')
    bone.head[:] = -0.7261, 1.3695, 0.0296
    bone.tail[:] = -0.7475, 1.3623, 0.0344
    bone.roll = -3.0798
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.01.R']]
    bones['thumb.02.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.R')
    bone.head[:] = -0.7962, 1.3972, -0.0006
    bone.tail[:] = -0.8176, 1.3827, -0.0003
    bone.roll = -1.5726
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.01.R']]
    bones['f_middle.02.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.R')
    bone.head[:] = -0.7937, 1.3939, -0.0240
    bone.tail[:] = -0.8112, 1.3799, -0.0242
    bone.roll = -1.5880
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.01.R']]
    bones['f_ring.02.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.R')
    bone.head[:] = -0.7799, 1.3976, -0.0473
    bone.tail[:] = -0.7922, 1.3862, -0.0480
    bone.roll = -1.4181
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.R']]
    bones['f_pinky.02.R'] = bone.name
    bone = arm.edit_bones.new('f_index.03.L')
    bone.head[:] = 0.8140, 1.3881, 0.0199
    bone.tail[:] = 0.8299, 1.3752, 0.0198
    bone.roll = 1.7519
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.02.L']]
    bones['f_index.03.L'] = bone.name
    bone = arm.edit_bones.new('thumb.03.L')
    bone.head[:] = 0.7475, 1.3623, 0.0344
    bone.tail[:] = 0.7655, 1.3565, 0.0373
    bone.roll = -3.0739
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.02.L']]
    bones['thumb.03.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.L')
    bone.head[:] = 0.8176, 1.3827, -0.0003
    bone.tail[:] = 0.8344, 1.3664, -0.0001
    bone.roll = 1.6010
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.02.L']]
    bones['f_middle.03.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.L')
    bone.head[:] = 0.8112, 1.3799, -0.0242
    bone.tail[:] = 0.8227, 1.3633, -0.0246
    bone.roll = 1.5973
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.02.L']]
    bones['f_ring.03.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.L')
    bone.head[:] = 0.7922, 1.3862, -0.0480
    bone.tail[:] = 0.7999, 1.3742, -0.0483
    bone.roll = 1.3293
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.L']]
    bones['f_pinky.03.L'] = bone.name
    bone = arm.edit_bones.new('f_index.03.R')
    bone.head[:] = -0.8140, 1.3881, 0.0199
    bone.tail[:] = -0.8299, 1.3752, 0.0198
    bone.roll = -1.7519
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.02.R']]
    bones['f_index.03.R'] = bone.name
    bone = arm.edit_bones.new('thumb.03.R')
    bone.head[:] = -0.7475, 1.3623, 0.0344
    bone.tail[:] = -0.7655, 1.3565, 0.0373
    bone.roll = 3.0739
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.02.R']]
    bones['thumb.03.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.R')
    bone.head[:] = -0.8176, 1.3827, -0.0003
    bone.tail[:] = -0.8344, 1.3664, -0.0001
    bone.roll = -1.6010
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.02.R']]
    bones['f_middle.03.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.R')
    bone.head[:] = -0.8112, 1.3799, -0.0242
    bone.tail[:] = -0.8227, 1.3633, -0.0246
    bone.roll = -1.5973
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.02.R']]
    bones['f_ring.03.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.R')
    bone.head[:] = -0.7922, 1.3862, -0.0480
    bone.tail[:] = -0.7999, 1.3742, -0.0483
    bone.roll = -1.3293
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.R']]
    bones['f_pinky.03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['hips']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Torso"].assign(pbone)
    try:
        pbone.gamerig.name = "torso"
    except AttributeError:
        pass
    try:
        pbone.gamerig.pivot_pos = 2
    except AttributeError:
        pass
    try:
        pbone.gamerig.neck_pos = 5
    except AttributeError:
        pass
    try:
        pbone.gamerig.stretchable_tweak = False
    except AttributeError:
        pass
    try:
        pbone.gamerig.tweak_bone_collection = "Torso (Tweak)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['waist']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Torso"].assign(pbone)
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.L (IK)"].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.L (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.R (IK)"].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.R (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    try:
        pbone.gamerig.footprint_bone = "JIG-heel.R"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['chest']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Torso"].assign(pbone)
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.L (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.R (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['upper_chest']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Torso"].assign(pbone)
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.L (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.R (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    arm.collections["Torso"].assign(pbone)
    try:
        pbone.gamerig.name = "generic"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    arm.collections["Torso"].assign(pbone)
    try:
        pbone.gamerig.name = "generic"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['neck']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Torso"].assign(pbone)
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.L (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.L (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.R (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Leg.R (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Arm.L (IK)"].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.L (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Arm.R (IK)"].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.R (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Torso"].assign(pbone)
    try:
        pbone.gamerig.name = "face"
    except AttributeError:
        pass
    try:
        pbone.gamerig.primary_bone_collection = "Face (Primary)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.secondary_bone_collection = "Face (Secondary)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Arm.L (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Arm.R (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['eye.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Face"].assign(pbone)
    pbone = obj.pose.bones[bones['eye.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Face"].assign(pbone)
    pbone = obj.pose.bones[bones['jaw']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Face"].assign(pbone)
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Arm.L (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['hand.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Arm.R (IK)"].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    try:
        pbone.gamerig.name = "thumb"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    try:
        pbone.gamerig.name = "thumb"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.L"].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections["Fingers.R"].assign(pbone)

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

    # arm.layers = [(x in [0, 3, 5, 8, 12, 16, 20]) for x in range(32)]

if __name__ == "__main__":
    create(bpy.context.active_object)
