import bpy


def create(obj):
    # generated by gamerig.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(28):
        arm.gamerig_layers.add()

    arm.gamerig_layers[0].name = "Face"
    arm.gamerig_layers[0].row = 1
    arm.gamerig_layers[1].name = "Face (Primary)"
    arm.gamerig_layers[1].row = 2
    arm.gamerig_layers[2].name = "Face (Secondary)"
    arm.gamerig_layers[2].row = 2
    arm.gamerig_layers[3].name = "Torso"
    arm.gamerig_layers[3].row = 3
    arm.gamerig_layers[4].name = "Torso (Tweak)"
    arm.gamerig_layers[4].row = 4
    arm.gamerig_layers[5].name = "Fingers"
    arm.gamerig_layers[5].row = 5
    arm.gamerig_layers[6].name = "Fingers (Tweak)"
    arm.gamerig_layers[6].row = 6
    arm.gamerig_layers[7].name = "Arm.L (IK)"
    arm.gamerig_layers[7].row = 7
    arm.gamerig_layers[8].name = "Arm.L (FK)"
    arm.gamerig_layers[8].row = 8
    arm.gamerig_layers[9].name = "Arm.L (Tweak)"
    arm.gamerig_layers[9].row = 9
    arm.gamerig_layers[10].name = "Arm.R (IK)"
    arm.gamerig_layers[10].row = 7
    arm.gamerig_layers[11].name = "Arm.R (FK)"
    arm.gamerig_layers[11].row = 8
    arm.gamerig_layers[12].name = "Arm.R (Tweak)"
    arm.gamerig_layers[12].row = 9
    arm.gamerig_layers[13].name = "Leg.L (IK)"
    arm.gamerig_layers[13].row = 10
    arm.gamerig_layers[14].name = "Leg.L (FK)"
    arm.gamerig_layers[14].row = 11
    arm.gamerig_layers[15].name = "Leg.L (Tweak)"
    arm.gamerig_layers[15].row = 12
    arm.gamerig_layers[16].name = "Leg.R (IK)"
    arm.gamerig_layers[16].row = 10
    arm.gamerig_layers[17].name = "Leg.R (FK)"
    arm.gamerig_layers[17].row = 11
    arm.gamerig_layers[18].name = "Leg.R (Tweak)"
    arm.gamerig_layers[18].row = 12
    arm.gamerig_layers[19].name = ""
    arm.gamerig_layers[19].row = 1
    arm.gamerig_layers[20].name = ""
    arm.gamerig_layers[20].row = 1
    arm.gamerig_layers[21].name = ""
    arm.gamerig_layers[21].row = 1
    arm.gamerig_layers[22].name = ""
    arm.gamerig_layers[22].row = 1
    arm.gamerig_layers[23].name = ""
    arm.gamerig_layers[23].row = 1
    arm.gamerig_layers[24].name = ""
    arm.gamerig_layers[24].row = 1
    arm.gamerig_layers[25].name = ""
    arm.gamerig_layers[25].row = 1
    arm.gamerig_layers[26].name = ""
    arm.gamerig_layers[26].row = 1
    arm.gamerig_layers[27].name = ""
    arm.gamerig_layers[27].row = 1

    arm.gamerig_rig_ui_template = 'ui_template'


    bones = {}

    bone = arm.edit_bones.new('ORG-hips')
    bone.head[:] = 0.0000, 0.0552, 1.0099
    bone.tail[:] = 0.0000, -0.0037, 1.2361
    bone.roll = 0.0000
    bone.use_connect = False
    bones['ORG-hips'] = bone.name
    bone = arm.edit_bones.new('ORG-waist')
    bone.head[:] = 0.0000, -0.0037, 1.2361
    bone.tail[:] = 0.0000, -0.0115, 1.3630
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-hips']]
    bones['ORG-waist'] = bone.name
    bone = arm.edit_bones.new('ORG-thigh.L')
    bone.head[:] = 0.0980, 0.0124, 1.0720
    bone.tail[:] = 0.0980, -0.0286, 0.5372
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hips']]
    bones['ORG-thigh.L'] = bone.name
    bone = arm.edit_bones.new('ORG-thigh.R')
    bone.head[:] = -0.0980, 0.0124, 1.0720
    bone.tail[:] = -0.0980, -0.0286, 0.5372
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hips']]
    bones['ORG-thigh.R'] = bone.name
    bone = arm.edit_bones.new('ORG-chest')
    bone.head[:] = 0.0000, -0.0115, 1.3630
    bone.tail[:] = 0.0000, -0.0025, 1.4719
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-waist']]
    bones['ORG-chest'] = bone.name
    bone = arm.edit_bones.new('ORG-shin.L')
    bone.head[:] = 0.0980, -0.0286, 0.5372
    bone.tail[:] = 0.0980, 0.0162, 0.0852
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-thigh.L']]
    bones['ORG-shin.L'] = bone.name
    bone = arm.edit_bones.new('ORG-shin.R')
    bone.head[:] = -0.0980, -0.0286, 0.5372
    bone.tail[:] = -0.0980, 0.0162, 0.0852
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-thigh.R']]
    bones['ORG-shin.R'] = bone.name
    bone = arm.edit_bones.new('ORG-upper_chest')
    bone.head[:] = 0.0000, -0.0025, 1.4719
    bone.tail[:] = 0.0000, 0.0114, 1.6582
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-chest']]
    bones['ORG-upper_chest'] = bone.name
    bone = arm.edit_bones.new('ORG-foot.L')
    bone.head[:] = 0.0980, 0.0162, 0.0852
    bone.tail[:] = 0.0980, -0.0934, 0.0167
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-shin.L']]
    bones['ORG-foot.L'] = bone.name
    bone = arm.edit_bones.new('ORG-foot.R')
    bone.head[:] = -0.0980, 0.0162, 0.0852
    bone.tail[:] = -0.0980, -0.0934, 0.0167
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-shin.R']]
    bones['ORG-foot.R'] = bone.name
    bone = arm.edit_bones.new('ORG-shoulder.L')
    bone.head[:] = 0.0183, -0.0684, 1.6051
    bone.tail[:] = 0.1694, 0.0205, 1.6050
    bone.roll = 0.0004
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-upper_chest']]
    bones['ORG-shoulder.L'] = bone.name
    bone = arm.edit_bones.new('ORG-shoulder.R')
    bone.head[:] = -0.0183, -0.0684, 1.6051
    bone.tail[:] = -0.1694, 0.0205, 1.6050
    bone.roll = -0.0004
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-upper_chest']]
    bones['ORG-shoulder.R'] = bone.name
    bone = arm.edit_bones.new('ORG-neck')
    bone.head[:] = 0.0000, 0.0114, 1.6582
    bone.tail[:] = 0.0000, -0.0247, 1.7813
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-upper_chest']]
    bones['ORG-neck'] = bone.name
    bone = arm.edit_bones.new('ORG-toe.L')
    bone.head[:] = 0.0980, -0.0934, 0.0167
    bone.tail[:] = 0.0980, -0.1606, 0.0162
    bone.roll = 3.1415
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-foot.L']]
    bones['ORG-toe.L'] = bone.name
    bone = arm.edit_bones.new('ORG-heel.L')
    bone.head[:] = 0.0600, 0.0459, 0.0000
    bone.tail[:] = 0.1400, 0.0459, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-foot.L']]
    bones['ORG-heel.L'] = bone.name
    bone = arm.edit_bones.new('ORG-toe.R')
    bone.head[:] = -0.0980, -0.0934, 0.0167
    bone.tail[:] = -0.0980, -0.1606, 0.0162
    bone.roll = 3.1415
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-foot.R']]
    bones['ORG-toe.R'] = bone.name
    bone = arm.edit_bones.new('ORG-heel.R')
    bone.head[:] = -0.0600, 0.0459, 0.0000
    bone.tail[:] = -0.1400, 0.0459, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-foot.R']]
    bones['ORG-heel.R'] = bone.name
    bone = arm.edit_bones.new('ORG-upper_arm.L')
    bone.head[:] = 0.1953, 0.0267, 1.5846
    bone.tail[:] = 0.4424, 0.0885, 1.4491
    bone.roll = 2.0724
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-shoulder.L']]
    bones['ORG-upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('ORG-upper_arm.R')
    bone.head[:] = -0.1953, 0.0267, 1.5846
    bone.tail[:] = -0.4424, 0.0885, 1.4491
    bone.roll = -2.0724
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-shoulder.R']]
    bones['ORG-upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('ORG-head')
    bone.head[:] = 0.0000, -0.0247, 1.7813
    bone.tail[:] = 0.0000, -0.0247, 1.9796
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-neck']]
    bones['ORG-head'] = bone.name
    bone = arm.edit_bones.new('ORG-forearm.L')
    bone.head[:] = 0.4424, 0.0885, 1.4491
    bone.tail[:] = 0.6594, 0.0492, 1.3061
    bone.roll = 2.1535
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-upper_arm.L']]
    bones['ORG-forearm.L'] = bone.name
    bone = arm.edit_bones.new('ORG-forearm.R')
    bone.head[:] = -0.4424, 0.0885, 1.4491
    bone.tail[:] = -0.6594, 0.0492, 1.3061
    bone.roll = -2.1535
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-upper_arm.R']]
    bones['ORG-forearm.R'] = bone.name
    bone = arm.edit_bones.new('ORG-eye.L')
    bone.head[:] = 0.0516, -0.1209, 1.8941
    bone.tail[:] = 0.0516, -0.1451, 1.8941
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-head']]
    bones['ORG-eye.L'] = bone.name
    bone = arm.edit_bones.new('ORG-eye.R')
    bone.head[:] = -0.0516, -0.1209, 1.8941
    bone.tail[:] = -0.0516, -0.1451, 1.8941
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-head']]
    bones['ORG-eye.R'] = bone.name
    bone = arm.edit_bones.new('ORG-jaw')
    bone.head[:] = -0.0000, -0.0243, 1.8300
    bone.tail[:] = -0.0000, -0.1328, 1.7862
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-head']]
    bones['ORG-jaw'] = bone.name
    bone = arm.edit_bones.new('ORG-hand.L')
    bone.head[:] = 0.6594, 0.0492, 1.3061
    bone.tail[:] = 0.7234, 0.0412, 1.2585
    bone.roll = 2.2103
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-forearm.L']]
    bones['ORG-hand.L'] = bone.name
    bone = arm.edit_bones.new('ORG-hand.R')
    bone.head[:] = -0.6594, 0.0492, 1.3061
    bone.tail[:] = -0.7234, 0.0412, 1.2585
    bone.roll = -2.2103
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-forearm.R']]
    bones['ORG-hand.R'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.01.L')
    bone.head[:] = 0.6921, 0.0224, 1.2882
    bone.tail[:] = 0.7464, 0.0051, 1.2482
    bone.roll = -2.4928
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.L']]
    bones['ORG-palm.01.L'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.02.L')
    bone.head[:] = 0.6970, 0.0389, 1.2877
    bone.tail[:] = 0.7525, 0.0277, 1.2487
    bone.roll = -2.5348
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.L']]
    bones['ORG-palm.02.L'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.03.L')
    bone.head[:] = 0.6963, 0.0545, 1.2874
    bone.tail[:] = 0.7540, 0.0521, 1.2482
    bone.roll = -2.5843
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.L']]
    bones['ORG-palm.03.L'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.04.L')
    bone.head[:] = 0.6929, 0.0696, 1.2871
    bone.tail[:] = 0.7528, 0.0763, 1.2467
    bone.roll = -2.5546
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.L']]
    bones['ORG-palm.04.L'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.01.R')
    bone.head[:] = -0.6921, 0.0224, 1.2882
    bone.tail[:] = -0.7464, 0.0051, 1.2482
    bone.roll = 2.4928
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.R']]
    bones['ORG-palm.01.R'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.02.R')
    bone.head[:] = -0.6970, 0.0389, 1.2877
    bone.tail[:] = -0.7525, 0.0277, 1.2487
    bone.roll = 2.5348
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.R']]
    bones['ORG-palm.02.R'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.03.R')
    bone.head[:] = -0.6963, 0.0545, 1.2874
    bone.tail[:] = -0.7540, 0.0521, 1.2482
    bone.roll = 2.5843
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.R']]
    bones['ORG-palm.03.R'] = bone.name
    bone = arm.edit_bones.new('ORG-palm.04.R')
    bone.head[:] = -0.6929, 0.0696, 1.2871
    bone.tail[:] = -0.7528, 0.0763, 1.2467
    bone.roll = 2.5546
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-hand.R']]
    bones['ORG-palm.04.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_index.01.L')
    bone.head[:] = 0.7464, 0.0051, 1.2482
    bone.tail[:] = 0.7725, 0.0009, 1.2099
    bone.roll = -2.0289
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.01.L']]
    bones['ORG-f_index.01.L'] = bone.name
    bone = arm.edit_bones.new('ORG-thumb.01.L')
    bone.head[:] = 0.6705, 0.0157, 1.2738
    bone.tail[:] = 0.6930, -0.0050, 1.2352
    bone.roll = -0.5295
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.01.L']]
    bones['ORG-thumb.01.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_middle.01.L')
    bone.head[:] = 0.7525, 0.0277, 1.2487
    bone.tail[:] = 0.7762, 0.0234, 1.2058
    bone.roll = -1.9923
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.02.L']]
    bones['ORG-f_middle.01.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_ring.01.L')
    bone.head[:] = 0.7540, 0.0521, 1.2482
    bone.tail[:] = 0.7735, 0.0498, 1.2046
    bone.roll = -2.0285
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.03.L']]
    bones['ORG-f_ring.01.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_pinky.01.L')
    bone.head[:] = 0.7528, 0.0763, 1.2467
    bone.tail[:] = 0.7657, 0.0764, 1.2172
    bone.roll = -1.9213
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.04.L']]
    bones['ORG-f_pinky.01.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_index.01.R')
    bone.head[:] = -0.7464, 0.0051, 1.2482
    bone.tail[:] = -0.7725, 0.0009, 1.2099
    bone.roll = 2.0289
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.01.R']]
    bones['ORG-f_index.01.R'] = bone.name
    bone = arm.edit_bones.new('ORG-thumb.01.R')
    bone.head[:] = -0.6705, 0.0157, 1.2738
    bone.tail[:] = -0.6930, -0.0050, 1.2352
    bone.roll = 0.5295
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.01.R']]
    bones['ORG-thumb.01.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_middle.01.R')
    bone.head[:] = -0.7525, 0.0277, 1.2487
    bone.tail[:] = -0.7762, 0.0234, 1.2058
    bone.roll = 1.9923
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.02.R']]
    bones['ORG-f_middle.01.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_ring.01.R')
    bone.head[:] = -0.7540, 0.0521, 1.2482
    bone.tail[:] = -0.7735, 0.0498, 1.2046
    bone.roll = 2.0285
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.03.R']]
    bones['ORG-f_ring.01.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_pinky.01.R')
    bone.head[:] = -0.7528, 0.0763, 1.2467
    bone.tail[:] = -0.7657, 0.0764, 1.2172
    bone.roll = 1.9213
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['ORG-palm.04.R']]
    bones['ORG-f_pinky.01.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_index.02.L')
    bone.head[:] = 0.7725, 0.0009, 1.2099
    bone.tail[:] = 0.7840, -0.0003, 1.1858
    bone.roll = -1.8753
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_index.01.L']]
    bones['ORG-f_index.02.L'] = bone.name
    bone = arm.edit_bones.new('ORG-thumb.02.L')
    bone.head[:] = 0.6930, -0.0050, 1.2352
    bone.tail[:] = 0.7065, -0.0114, 1.2142
    bone.roll = -0.5370
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-thumb.01.L']]
    bones['ORG-thumb.02.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_middle.02.L')
    bone.head[:] = 0.7762, 0.0234, 1.2058
    bone.tail[:] = 0.7851, 0.0221, 1.1785
    bone.roll = -1.8640
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_middle.01.L']]
    bones['ORG-f_middle.02.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_ring.02.L')
    bone.head[:] = 0.7735, 0.0498, 1.2046
    bone.tail[:] = 0.7794, 0.0494, 1.1803
    bone.roll = -1.7621
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_ring.01.L']]
    bones['ORG-f_ring.02.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_pinky.02.L')
    bone.head[:] = 0.7657, 0.0764, 1.2172
    bone.tail[:] = 0.7686, 0.0769, 1.1986
    bone.roll = -1.7397
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_pinky.01.L']]
    bones['ORG-f_pinky.02.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_index.02.R')
    bone.head[:] = -0.7725, 0.0009, 1.2099
    bone.tail[:] = -0.7840, -0.0003, 1.1858
    bone.roll = 1.8753
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_index.01.R']]
    bones['ORG-f_index.02.R'] = bone.name
    bone = arm.edit_bones.new('ORG-thumb.02.R')
    bone.head[:] = -0.6930, -0.0050, 1.2352
    bone.tail[:] = -0.7065, -0.0114, 1.2142
    bone.roll = 0.5370
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-thumb.01.R']]
    bones['ORG-thumb.02.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_middle.02.R')
    bone.head[:] = -0.7762, 0.0234, 1.2058
    bone.tail[:] = -0.7851, 0.0221, 1.1785
    bone.roll = 1.8640
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_middle.01.R']]
    bones['ORG-f_middle.02.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_ring.02.R')
    bone.head[:] = -0.7735, 0.0498, 1.2046
    bone.tail[:] = -0.7794, 0.0494, 1.1803
    bone.roll = 1.7621
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_ring.01.R']]
    bones['ORG-f_ring.02.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_pinky.02.R')
    bone.head[:] = -0.7657, 0.0764, 1.2172
    bone.tail[:] = -0.7686, 0.0769, 1.1986
    bone.roll = 1.7397
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_pinky.01.R']]
    bones['ORG-f_pinky.02.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_index.03.L')
    bone.head[:] = 0.7840, -0.0003, 1.1858
    bone.tail[:] = 0.7892, -0.0006, 1.1636
    bone.roll = -1.6760
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_index.02.L']]
    bones['ORG-f_index.03.L'] = bone.name
    bone = arm.edit_bones.new('ORG-thumb.03.L')
    bone.head[:] = 0.7065, -0.0114, 1.2142
    bone.tail[:] = 0.7182, -0.0155, 1.1968
    bone.roll = -0.5182
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-thumb.02.L']]
    bones['ORG-thumb.03.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_middle.03.L')
    bone.head[:] = 0.7851, 0.0221, 1.1785
    bone.tail[:] = 0.7888, 0.0216, 1.1525
    bone.roll = -1.7267
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_middle.02.L']]
    bones['ORG-f_middle.03.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_ring.03.L')
    bone.head[:] = 0.7794, 0.0494, 1.1803
    bone.tail[:] = 0.7781, 0.0498, 1.1577
    bone.roll = -1.5224
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_ring.02.L']]
    bones['ORG-f_ring.03.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_pinky.03.L')
    bone.head[:] = 0.7686, 0.0769, 1.1986
    bone.tail[:] = 0.7673, 0.0772, 1.1828
    bone.roll = -1.4827
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_pinky.02.L']]
    bones['ORG-f_pinky.03.L'] = bone.name
    bone = arm.edit_bones.new('ORG-f_index.03.R')
    bone.head[:] = -0.7840, -0.0003, 1.1858
    bone.tail[:] = -0.7892, -0.0006, 1.1636
    bone.roll = 1.6760
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_index.02.R']]
    bones['ORG-f_index.03.R'] = bone.name
    bone = arm.edit_bones.new('ORG-thumb.03.R')
    bone.head[:] = -0.7065, -0.0114, 1.2142
    bone.tail[:] = -0.7182, -0.0155, 1.1968
    bone.roll = 0.5182
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-thumb.02.R']]
    bones['ORG-thumb.03.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_middle.03.R')
    bone.head[:] = -0.7851, 0.0221, 1.1785
    bone.tail[:] = -0.7888, 0.0216, 1.1525
    bone.roll = 1.7267
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_middle.02.R']]
    bones['ORG-f_middle.03.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_ring.03.R')
    bone.head[:] = -0.7794, 0.0494, 1.1803
    bone.tail[:] = -0.7781, 0.0498, 1.1577
    bone.roll = 1.5224
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_ring.02.R']]
    bones['ORG-f_ring.03.R'] = bone.name
    bone = arm.edit_bones.new('ORG-f_pinky.03.R')
    bone.head[:] = -0.7686, 0.0769, 1.1986
    bone.tail[:] = -0.7673, 0.0772, 1.1828
    bone.roll = 1.4827
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['ORG-f_pinky.02.R']]
    bones['ORG-f_pinky.03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['ORG-hips']]
    pbone.gamerig_type = 'torso'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.pivot_pos = 2
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.neck_pos = 5
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_layers = [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.chain_bone_controls = ""
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-waist']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-thigh.L']]
    pbone.gamerig_type = 'limbs.limb'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_ik_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.ik_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.separate_hose_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.hose_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.limb_type = "leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.fk_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-thigh.R']]
    pbone.gamerig_type = 'limbs.limb'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_ik_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.ik_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.separate_hose_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.hose_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.fk_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.limb_type = "leg"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-chest']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-shin.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-shin.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-upper_chest']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-foot.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-foot.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-shoulder.L']]
    pbone.gamerig_type = 'copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-shoulder.R']]
    pbone.gamerig_type = 'copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-neck']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-toe.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-heel.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-toe.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-heel.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-upper_arm.L']]
    pbone.gamerig_type = 'limbs.limb'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_ik_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.ik_layers = [False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.separate_hose_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.hose_layers = [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.fk_layers = [False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-upper_arm.R']]
    pbone.gamerig_type = 'limbs.limb'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_ik_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.ik_layers = [False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.separate_hose_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.hose_layers = [False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.fk_layers = [False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-head']]
    pbone.gamerig_type = 'face'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.secondary_layers = [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-forearm.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-forearm.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-eye.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-eye.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-jaw']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, True, False, True, False, True, False, False, True, False, False, True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-hand.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-hand.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.01.L']]
    pbone.gamerig_type = 'palm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.02.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.03.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.04.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.01.R']]
    pbone.gamerig_type = 'palm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.02.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.03.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-palm.04.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_index.01.L']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-thumb.01.L']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_middle.01.L']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_ring.01.L']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_pinky.01.L']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_index.01.R']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-thumb.01.R']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_middle.01.R']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_ring.01.R']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_pinky.01.R']]
    pbone.gamerig_type = 'finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.gamerig_parameters.separate_extra_layers = True
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.extra_layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.gamerig_parameters.tweak_extra_layers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['ORG-f_index.02.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-thumb.02.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_middle.02.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_ring.02.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_pinky.02.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_index.02.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-thumb.02.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_middle.02.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_ring.02.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_pinky.02.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_index.03.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-thumb.03.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_middle.03.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_ring.03.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_pinky.03.L']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_index.03.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-thumb.03.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_middle.03.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_ring.03.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['ORG-f_pinky.03.R']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

    arm.layers = [(x in [0, 3, 5, 7, 10, 13, 16]) for x in range(32)]

if __name__ == "__main__":
    create(bpy.context.active_object)