import bpy


from mathutils import Color


def create(obj):
    # generated by gamerig.utils.write_metarig

    obj.rotation_mode     = 'XYZ'
    obj.rotation_euler      = (0.0, 0.0, 0.0)
    obj.rotation_quaternion = (1.0, 0.0, 0.0, 0.0)
    obj.rotation_axis_angle = (0.0, 0.0, 1.0, 0.0)

    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    arm.gamerig.rig_ui_template = 'ui_template'

    for i in range(6):
        arm.gamerig.colors.add()

    arm.gamerig.colors[0].name = "Root"
    arm.gamerig.colors[0].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[0].normal = Color((0.4352940022945404, 0.18431399762630463, 0.4156860113143921))
    arm.gamerig.colors[0].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[0].standard_colors_lock = True
    arm.gamerig.colors[1].name = "IK"
    arm.gamerig.colors[1].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[1].normal = Color((0.6039220094680786, 0.0, 0.0))
    arm.gamerig.colors[1].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[1].standard_colors_lock = True
    arm.gamerig.colors[2].name = "Special"
    arm.gamerig.colors[2].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[2].normal = Color((0.9568629860877991, 0.7882350087165833, 0.04705899953842163))
    arm.gamerig.colors[2].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[2].standard_colors_lock = True
    arm.gamerig.colors[3].name = "Tweak"
    arm.gamerig.colors[3].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[3].normal = Color((0.03921600058674812, 0.21176500618457794, 0.5803920030593872))
    arm.gamerig.colors[3].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[3].standard_colors_lock = True
    arm.gamerig.colors[4].name = "FK"
    arm.gamerig.colors[4].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[4].normal = Color((0.11764699965715408, 0.5686269998550415, 0.035294000059366226))
    arm.gamerig.colors[4].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[4].standard_colors_lock = True
    arm.gamerig.colors[5].name = "Extra"
    arm.gamerig.colors[5].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[5].normal = Color((0.9686279892921448, 0.2509799897670746, 0.09411799907684326))
    arm.gamerig.colors[5].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[5].standard_colors_lock = True

    if len(arm.collections) > 0:
        for i in arm.collections:
            arm.collections.remove(i)
    arm.collections.new("Face")
    arm.collections[-1].gamerig.row = 1
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Face (Primary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Face (Secondary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Torso")
    arm.collections[-1].gamerig.row = 3
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Torso (Tweak)")
    arm.collections[-1].gamerig.row = 4
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Fingers.L")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Fingers.R")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Arm.L (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.L (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Arm.R (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.R (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.L (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.L (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.R (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.R (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Root")
    arm.collections[-1].gamerig.row = 14
    arm.collections[-1].gamerig.group = 1

    bones = {}

    bone = arm.edit_bones.new('hips')
    bone.head[:] = 0.0000, 0.0337, 0.9062
    bone.tail[:] = 0.0000, -0.0052, 1.0803
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bones['hips'] = bone.name
    bone = arm.edit_bones.new('waist')
    bone.head[:] = 0.0000, -0.0052, 1.0803
    bone.tail[:] = 0.0000, -0.0103, 1.1916
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['waist'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head[:] = 0.0877, -0.0039, 0.9470
    bone.tail[:] = 0.1670, -0.0256, 0.4750
    bone.roll = -0.1792
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head[:] = -0.0877, -0.0039, 0.9470
    bone.tail[:] = -0.1670, -0.0256, 0.4750
    bone.roll = 0.1792
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('chest')
    bone.head[:] = 0.0000, -0.0103, 1.1916
    bone.tail[:] = 0.0000, -0.0071, 1.3049
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['waist']]
    bones['chest'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head[:] = 0.1670, -0.0256, 0.4750
    bone.tail[:] = 0.2340, 0.0145, 0.0761
    bone.roll = -0.1500
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head[:] = -0.1670, -0.0256, 0.4750
    bone.tail[:] = -0.2340, 0.0145, 0.0761
    bone.roll = 0.1500
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('upper_chest')
    bone.head[:] = 0.0000, -0.0071, 1.3049
    bone.tail[:] = 0.0000, 0.0102, 1.4716
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['chest']]
    bones['upper_chest'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head[:] = 0.2340, 0.0145, 0.0761
    bone.tail[:] = 0.2353, -0.0836, 0.0156
    bone.roll = -0.0381
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head[:] = -0.2340, 0.0145, 0.0761
    bone.tail[:] = -0.2353, -0.0836, 0.0156
    bone.roll = 0.0381
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('shoulder.L')
    bone.head[:] = 0.0216, -0.0031, 1.4241
    bone.tail[:] = 0.1516, 0.0183, 1.4240
    bone.roll = 0.0004
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_chest']]
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('shoulder.R')
    bone.head[:] = -0.0216, -0.0031, 1.4241
    bone.tail[:] = -0.1516, 0.0183, 1.4240
    bone.roll = -0.0004
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_chest']]
    bones['shoulder.R'] = bone.name
    bone = arm.edit_bones.new('neck')
    bone.head[:] = 0.0000, 0.0102, 1.4716
    bone.tail[:] = 0.0000, 0.0015, 1.5619
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_chest']]
    bones['neck'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head[:] = 0.2353, -0.0836, 0.0156
    bone.tail[:] = 0.2354, -0.1437, 0.0151
    bone.roll = -0.3974
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('JIG-heel.L')
    bone.head[:] = 0.1979, 0.0411, -0.0000
    bone.tail[:] = 0.2695, 0.0411, -0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.use_deform = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['JIG-heel.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head[:] = -0.2353, -0.0836, 0.0156
    bone.tail[:] = -0.2354, -0.1437, 0.0151
    bone.roll = 0.3974
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('JIG-heel.R')
    bone.head[:] = -0.1979, 0.0411, -0.0000
    bone.tail[:] = -0.2695, 0.0411, -0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['JIG-heel.R'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head[:] = 0.1748, 0.0239, 1.4057
    bone.tail[:] = 0.3542, 0.0465, 1.2201
    bone.roll = 2.3100
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head[:] = -0.1748, 0.0239, 1.4057
    bone.tail[:] = -0.3542, 0.0465, 1.2201
    bone.roll = -2.3100
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shoulder.R']]
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head[:] = 0.0000, 0.0015, 1.5619
    bone.tail[:] = 0.0000, 0.0015, 1.7394
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['neck']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head[:] = 0.3542, 0.0465, 1.2201
    bone.tail[:] = 0.5177, 0.0144, 1.0509
    bone.roll = 2.3100
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head[:] = -0.3542, 0.0465, 1.2201
    bone.tail[:] = -0.5177, 0.0144, 1.0509
    bone.roll = -2.3100
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('eye.L')
    bone.head[:] = 0.0462, -0.0721, 1.6629
    bone.tail[:] = 0.0462, -0.0938, 1.6629
    bone.roll = -0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.L'] = bone.name
    bone = arm.edit_bones.new('eye.R')
    bone.head[:] = -0.0462, -0.0721, 1.6629
    bone.tail[:] = -0.0462, -0.0938, 1.6629
    bone.roll = -0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.R'] = bone.name
    bone = arm.edit_bones.new('jaw')
    bone.head[:] = 0.0000, 0.0018, 1.6055
    bone.tail[:] = 0.0000, -0.0828, 1.5663
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['head']]
    bones['jaw'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head[:] = 0.5177, 0.0144, 1.0509
    bone.tail[:] = 0.5674, 0.0156, 0.9993
    bone.roll = -2.3391
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('hand.R')
    bone.head[:] = -0.5177, 0.0144, 1.0509
    bone.tail[:] = -0.5674, 0.0156, 0.9993
    bone.roll = 2.3391
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['hand.R'] = bone.name
    bone = arm.edit_bones.new('palm.01.L')
    bone.head[:] = 0.5427, -0.0054, 1.0421
    bone.tail[:] = 0.5875, -0.0166, 1.0002
    bone.roll = -2.1782
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.01.L'] = bone.name
    bone = arm.edit_bones.new('palm.02.L')
    bone.head[:] = 0.5458, 0.0097, 1.0413
    bone.tail[:] = 0.5913, 0.0040, 1.0003
    bone.roll = -2.3202
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.02.L'] = bone.name
    bone = arm.edit_bones.new('palm.03.L')
    bone.head[:] = 0.5441, 0.0235, 1.0414
    bone.tail[:] = 0.5909, 0.0258, 1.0001
    bone.roll = -2.4173
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.03.L'] = bone.name
    bone = arm.edit_bones.new('palm.04.L')
    bone.head[:] = 0.5401, 0.0368, 1.0418
    bone.tail[:] = 0.5879, 0.0473, 0.9993
    bone.roll = -2.6135
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.04.L'] = bone.name
    bone = arm.edit_bones.new('palm.01.R')
    bone.head[:] = -0.5427, -0.0054, 1.0421
    bone.tail[:] = -0.5875, -0.0166, 1.0002
    bone.roll = 2.1782
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.01.R'] = bone.name
    bone = arm.edit_bones.new('palm.02.R')
    bone.head[:] = -0.5458, 0.0097, 1.0413
    bone.tail[:] = -0.5913, 0.0040, 1.0003
    bone.roll = 2.3202
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.02.R'] = bone.name
    bone = arm.edit_bones.new('palm.03.R')
    bone.head[:] = -0.5441, 0.0235, 1.0414
    bone.tail[:] = -0.5909, 0.0258, 1.0001
    bone.roll = 2.4173
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.03.R'] = bone.name
    bone = arm.edit_bones.new('palm.04.R')
    bone.head[:] = -0.5401, 0.0368, 1.0418
    bone.tail[:] = -0.5879, 0.0473, 0.9993
    bone.roll = 2.6135
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.04.R'] = bone.name
    bone = arm.edit_bones.new('f_index.01.L')
    bone.head[:] = 0.5875, -0.0166, 1.0002
    bone.tail[:] = 0.6065, -0.0182, 0.9633
    bone.roll = -1.7372
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.01.L']]
    bones['f_index.01.L'] = bone.name
    bone = arm.edit_bones.new('thumb.01.L')
    bone.head[:] = 0.5221, -0.0127, 1.0267
    bone.tail[:] = 0.5390, -0.0291, 0.9896
    bone.roll = -0.3086
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.01.L']]
    bones['thumb.01.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.L')
    bone.head[:] = 0.5913, 0.0040, 1.0003
    bone.tail[:] = 0.6077, 0.0021, 0.9596
    bone.roll = -1.8405
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.02.L']]
    bones['f_middle.01.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.L')
    bone.head[:] = 0.5909, 0.0258, 1.0001
    bone.tail[:] = 0.6034, 0.0255, 0.9592
    bone.roll = -1.8472
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.03.L']]
    bones['f_ring.01.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.L')
    bone.head[:] = 0.5879, 0.0473, 0.9993
    bone.tail[:] = 0.5959, 0.0486, 0.9716
    bone.roll = -2.1653
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.04.L']]
    bones['f_pinky.01.L'] = bone.name
    bone = arm.edit_bones.new('f_index.01.R')
    bone.head[:] = -0.5875, -0.0166, 1.0002
    bone.tail[:] = -0.6065, -0.0182, 0.9633
    bone.roll = 1.7372
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.01.R']]
    bones['f_index.01.R'] = bone.name
    bone = arm.edit_bones.new('thumb.01.R')
    bone.head[:] = -0.5221, -0.0127, 1.0267
    bone.tail[:] = -0.5390, -0.0291, 0.9896
    bone.roll = 0.3086
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.01.R']]
    bones['thumb.01.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.R')
    bone.head[:] = -0.5913, 0.0040, 1.0003
    bone.tail[:] = -0.6077, 0.0021, 0.9596
    bone.roll = 1.8405
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.02.R']]
    bones['f_middle.01.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.R')
    bone.head[:] = -0.5909, 0.0258, 1.0001
    bone.tail[:] = -0.6034, 0.0255, 0.9592
    bone.roll = 1.8472
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.03.R']]
    bones['f_ring.01.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.R')
    bone.head[:] = -0.5879, 0.0473, 0.9993
    bone.tail[:] = -0.5959, 0.0486, 0.9716
    bone.roll = 2.1653
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['palm.04.R']]
    bones['f_pinky.01.R'] = bone.name
    bone = arm.edit_bones.new('f_index.02.L')
    bone.head[:] = 0.6065, -0.0182, 0.9633
    bone.tail[:] = 0.6141, -0.0183, 0.9405
    bone.roll = -1.7325
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.01.L']]
    bones['f_index.02.L'] = bone.name
    bone = arm.edit_bones.new('thumb.02.L')
    bone.head[:] = 0.5390, -0.0291, 0.9896
    bone.tail[:] = 0.5491, -0.0337, 0.9693
    bone.roll = -0.2424
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.01.L']]
    bones['thumb.02.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.L')
    bone.head[:] = 0.6077, 0.0021, 0.9596
    bone.tail[:] = 0.6126, 0.0019, 0.9342
    bone.roll = -1.7473
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.01.L']]
    bones['f_middle.02.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.L')
    bone.head[:] = 0.6034, 0.0255, 0.9592
    bone.tail[:] = 0.6058, 0.0257, 0.9369
    bone.roll = -1.6934
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.01.L']]
    bones['f_ring.02.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.L')
    bone.head[:] = 0.5959, 0.0486, 0.9716
    bone.tail[:] = 0.5965, 0.0494, 0.9548
    bone.roll = -1.8674
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.L']]
    bones['f_pinky.02.L'] = bone.name
    bone = arm.edit_bones.new('f_index.02.R')
    bone.head[:] = -0.6065, -0.0182, 0.9633
    bone.tail[:] = -0.6141, -0.0183, 0.9405
    bone.roll = 1.7325
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.01.R']]
    bones['f_index.02.R'] = bone.name
    bone = arm.edit_bones.new('thumb.02.R')
    bone.head[:] = -0.5390, -0.0291, 0.9896
    bone.tail[:] = -0.5491, -0.0337, 0.9693
    bone.roll = 0.2424
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.01.R']]
    bones['thumb.02.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.R')
    bone.head[:] = -0.6077, 0.0021, 0.9596
    bone.tail[:] = -0.6126, 0.0019, 0.9342
    bone.roll = 1.7473
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.01.R']]
    bones['f_middle.02.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.R')
    bone.head[:] = -0.6034, 0.0255, 0.9592
    bone.tail[:] = -0.6058, 0.0257, 0.9369
    bone.roll = 1.6934
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.01.R']]
    bones['f_ring.02.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.R')
    bone.head[:] = -0.5959, 0.0486, 0.9716
    bone.tail[:] = -0.5965, 0.0494, 0.9548
    bone.roll = 1.8674
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.R']]
    bones['f_pinky.02.R'] = bone.name
    bone = arm.edit_bones.new('f_index.03.L')
    bone.head[:] = 0.6141, -0.0183, 0.9405
    bone.tail[:] = 0.6162, -0.0181, 0.9201
    bone.roll = -1.5144
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.02.L']]
    bones['f_index.03.L'] = bone.name
    bone = arm.edit_bones.new('thumb.03.L')
    bone.head[:] = 0.5491, -0.0337, 0.9693
    bone.tail[:] = 0.5577, -0.0365, 0.9524
    bone.roll = -0.2069
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.02.L']]
    bones['thumb.03.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.L')
    bone.head[:] = 0.6126, 0.0019, 0.9342
    bone.tail[:] = 0.6129, 0.0018, 0.9108
    bone.roll = -1.5467
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.02.L']]
    bones['f_middle.03.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.L')
    bone.head[:] = 0.6058, 0.0257, 0.9369
    bone.tail[:] = 0.6022, 0.0262, 0.9170
    bone.roll = -1.4396
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.02.L']]
    bones['f_ring.03.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.L')
    bone.head[:] = 0.5965, 0.0494, 0.9548
    bone.tail[:] = 0.5935, 0.0496, 0.9410
    bone.roll = -1.6807
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.L']]
    bones['f_pinky.03.L'] = bone.name
    bone = arm.edit_bones.new('f_index.03.R')
    bone.head[:] = -0.6141, -0.0183, 0.9405
    bone.tail[:] = -0.6162, -0.0181, 0.9201
    bone.roll = 1.5144
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_index.02.R']]
    bones['f_index.03.R'] = bone.name
    bone = arm.edit_bones.new('thumb.03.R')
    bone.head[:] = -0.5491, -0.0337, 0.9693
    bone.tail[:] = -0.5577, -0.0365, 0.9524
    bone.roll = 0.2069
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thumb.02.R']]
    bones['thumb.03.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.R')
    bone.head[:] = -0.6126, 0.0019, 0.9342
    bone.tail[:] = -0.6129, 0.0018, 0.9108
    bone.roll = 1.5467
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_middle.02.R']]
    bones['f_middle.03.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.R')
    bone.head[:] = -0.6058, 0.0257, 0.9369
    bone.tail[:] = -0.6022, 0.0262, 0.9170
    bone.roll = 1.4396
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_ring.02.R']]
    bones['f_ring.03.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.R')
    bone.head[:] = -0.5965, 0.0494, 0.9548
    bone.tail[:] = -0.5935, 0.0496, 0.9410
    bone.roll = 1.6807
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.R']]
    bones['f_pinky.03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['hips']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "torso"
    except AttributeError:
        pass
    try:
        pbone.gamerig.pivot_pos = 2
    except AttributeError:
        pass
    try:
        pbone.gamerig.neck_pos = 5
    except AttributeError:
        pass
    try:
        pbone.gamerig.stretchable_tweak = False
    except AttributeError:
        pass
    try:
        pbone.gamerig.tweak_layers = [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['waist']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.L (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.R (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.footprint_bone = "JIG-heel.R"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['chest']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['upper_chest']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "generic"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "generic"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['neck']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.L (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.tweak_collection = "Arm.R (Tweak)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.R (FK)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Face'].assign(pbone)
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "face"
    except AttributeError:
        pass
    try:
        pbone.gamerig.primary_bone_collection = "Face (Primary)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.secondary_bone_collection = "Face (Secondary)"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['eye.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Face'].assign(pbone)
    pbone = obj.pose.bones[bones['eye.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Face'].assign(pbone)
    pbone = obj.pose.bones[bones['jaw']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Face'].assign(pbone)
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['hand.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['palm.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "palm"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['palm.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['palm.04.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['palm.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "palm"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['palm.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['palm.04.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "thumb"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "thumb"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    try:
        pbone.gamerig.name = "finger"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.02.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.02.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.03.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.L'].assign(pbone)
    pbone = obj.pose.bones[bones['f_index.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['thumb.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_middle.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_ring.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)
    pbone = obj.pose.bones[bones['f_pinky.03.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Fingers.R'].assign(pbone)

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

if __name__ == "__main__":
    create(bpy.context.active_object)
