import bpy


from mathutils import Color


def create(obj):
    # generated by gamerig.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    arm.gamerig_rig_ui_template = 'ui_template'

    for i in range(6):
        arm.gamerig_colors.add()

    arm.gamerig_colors[0].name = "Root"
    arm.gamerig_colors[0].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig_colors[0].normal = Color((0.4352940022945404, 0.18431399762630463, 0.4156860113143921))
    arm.gamerig_colors[0].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig_colors[0].standard_colors_lock = True
    arm.gamerig_colors[1].name = "IK"
    arm.gamerig_colors[1].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig_colors[1].normal = Color((0.6039220094680786, 0.0, 0.0))
    arm.gamerig_colors[1].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig_colors[1].standard_colors_lock = True
    arm.gamerig_colors[2].name = "Special"
    arm.gamerig_colors[2].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig_colors[2].normal = Color((0.9568629860877991, 0.7882350087165833, 0.04705899953842163))
    arm.gamerig_colors[2].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig_colors[2].standard_colors_lock = True
    arm.gamerig_colors[3].name = "Tweak"
    arm.gamerig_colors[3].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig_colors[3].normal = Color((0.03921600058674812, 0.21176500618457794, 0.5803920030593872))
    arm.gamerig_colors[3].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig_colors[3].standard_colors_lock = True
    arm.gamerig_colors[4].name = "FK"
    arm.gamerig_colors[4].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig_colors[4].normal = Color((0.11764699965715408, 0.5686269998550415, 0.035294000059366226))
    arm.gamerig_colors[4].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig_colors[4].standard_colors_lock = True
    arm.gamerig_colors[5].name = "Extra"
    arm.gamerig_colors[5].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig_colors[5].normal = Color((0.9686279892921448, 0.2509799897670746, 0.09411799907684326))
    arm.gamerig_colors[5].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig_colors[5].standard_colors_lock = True

    for i in range(29):
        arm.gamerig_layers.add()

    arm.gamerig_layers[0].name = "Face"
    arm.gamerig_layers[0].row = 1
    arm.gamerig_layers[0].set = False
    arm.gamerig_layers[0].group = 5
    arm.gamerig_layers[1].name = "Face (Primary)"
    arm.gamerig_layers[1].row = 2
    arm.gamerig_layers[1].set = False
    arm.gamerig_layers[1].group = 2
    arm.gamerig_layers[2].name = "Face (Secondary)"
    arm.gamerig_layers[2].row = 2
    arm.gamerig_layers[2].set = False
    arm.gamerig_layers[2].group = 3
    arm.gamerig_layers[3].name = "Torso"
    arm.gamerig_layers[3].row = 3
    arm.gamerig_layers[3].set = False
    arm.gamerig_layers[3].group = 3
    arm.gamerig_layers[4].name = "Torso (Tweak)"
    arm.gamerig_layers[4].row = 4
    arm.gamerig_layers[4].set = False
    arm.gamerig_layers[4].group = 4
    arm.gamerig_layers[5].name = "Fingers"
    arm.gamerig_layers[5].row = 5
    arm.gamerig_layers[5].set = False
    arm.gamerig_layers[5].group = 6
    arm.gamerig_layers[6].name = "Fingers (Tweak)"
    arm.gamerig_layers[6].row = 6
    arm.gamerig_layers[6].set = False
    arm.gamerig_layers[6].group = 4
    arm.gamerig_layers[7].name = "Arm.L (IK)"
    arm.gamerig_layers[7].row = 7
    arm.gamerig_layers[7].set = False
    arm.gamerig_layers[7].group = 2
    arm.gamerig_layers[8].name = "Arm.L (FK)"
    arm.gamerig_layers[8].row = 8
    arm.gamerig_layers[8].set = False
    arm.gamerig_layers[8].group = 5
    arm.gamerig_layers[9].name = "Arm.L (Tweak)"
    arm.gamerig_layers[9].row = 9
    arm.gamerig_layers[9].set = False
    arm.gamerig_layers[9].group = 4
    arm.gamerig_layers[10].name = "Arm.R (IK)"
    arm.gamerig_layers[10].row = 7
    arm.gamerig_layers[10].set = False
    arm.gamerig_layers[10].group = 2
    arm.gamerig_layers[11].name = "Arm.R (FK)"
    arm.gamerig_layers[11].row = 8
    arm.gamerig_layers[11].set = False
    arm.gamerig_layers[11].group = 5
    arm.gamerig_layers[12].name = "Arm.R (Tweak)"
    arm.gamerig_layers[12].row = 9
    arm.gamerig_layers[12].set = False
    arm.gamerig_layers[12].group = 4
    arm.gamerig_layers[13].name = "Leg.L (IK)"
    arm.gamerig_layers[13].row = 10
    arm.gamerig_layers[13].set = False
    arm.gamerig_layers[13].group = 2
    arm.gamerig_layers[14].name = "Leg.L (FK)"
    arm.gamerig_layers[14].row = 11
    arm.gamerig_layers[14].set = False
    arm.gamerig_layers[14].group = 5
    arm.gamerig_layers[15].name = "Leg.L (Tweak)"
    arm.gamerig_layers[15].row = 12
    arm.gamerig_layers[15].set = False
    arm.gamerig_layers[15].group = 4
    arm.gamerig_layers[16].name = "Leg.R (IK)"
    arm.gamerig_layers[16].row = 10
    arm.gamerig_layers[16].set = False
    arm.gamerig_layers[16].group = 2
    arm.gamerig_layers[17].name = "Leg.R (FK)"
    arm.gamerig_layers[17].row = 11
    arm.gamerig_layers[17].set = False
    arm.gamerig_layers[17].group = 5
    arm.gamerig_layers[18].name = "Leg.R (Tweak)"
    arm.gamerig_layers[18].row = 12
    arm.gamerig_layers[18].set = False
    arm.gamerig_layers[18].group = 4
    arm.gamerig_layers[19].name = ""
    arm.gamerig_layers[19].row = 1
    arm.gamerig_layers[19].set = False
    arm.gamerig_layers[19].group = 0
    arm.gamerig_layers[20].name = ""
    arm.gamerig_layers[20].row = 1
    arm.gamerig_layers[20].set = False
    arm.gamerig_layers[20].group = 0
    arm.gamerig_layers[21].name = ""
    arm.gamerig_layers[21].row = 1
    arm.gamerig_layers[21].set = False
    arm.gamerig_layers[21].group = 0
    arm.gamerig_layers[22].name = ""
    arm.gamerig_layers[22].row = 1
    arm.gamerig_layers[22].set = False
    arm.gamerig_layers[22].group = 0
    arm.gamerig_layers[23].name = ""
    arm.gamerig_layers[23].row = 1
    arm.gamerig_layers[23].set = False
    arm.gamerig_layers[23].group = 0
    arm.gamerig_layers[24].name = ""
    arm.gamerig_layers[24].row = 1
    arm.gamerig_layers[24].set = False
    arm.gamerig_layers[24].group = 0
    arm.gamerig_layers[25].name = ""
    arm.gamerig_layers[25].row = 1
    arm.gamerig_layers[25].set = False
    arm.gamerig_layers[25].group = 0
    arm.gamerig_layers[26].name = ""
    arm.gamerig_layers[26].row = 1
    arm.gamerig_layers[26].set = False
    arm.gamerig_layers[26].group = 0
    arm.gamerig_layers[27].name = ""
    arm.gamerig_layers[27].row = 1
    arm.gamerig_layers[27].set = False
    arm.gamerig_layers[27].group = 0
    arm.gamerig_layers[28].name = "Root"
    arm.gamerig_layers[28].row = 14
    arm.gamerig_layers[28].set = False
    arm.gamerig_layers[28].group = 1

    bones = {}

    bone = arm.edit_bones.new('Bone')
    bone.head[:] = 0.0000, 0.0000, 0.0000
    bone.tail[:] = 0.0000, 0.0000, 1.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bones['Bone'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Bone']]
    pbone.gamerig_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

    arm.layers = [(x in [0]) for x in range(32)]

if __name__ == "__main__":
    create(bpy.context.active_object)
