import bpy


from mathutils import Color


def create(obj):
    # generated by gamerig.utils.write_metarig

    obj.rotation_mode     = 'XYZ'
    obj.rotation_euler      = (0.0, 0.0, 0.0)
    obj.rotation_quaternion = (1.0, 0.0, 0.0, 0.0)
    obj.rotation_axis_angle = (0.0, 0.0, 1.0, 0.0)

    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    arm.gamerig.rig_ui_template = 'ui_template'

    for i in range(6):
        arm.gamerig.colors.add()

    arm.gamerig.colors[0].name = "Root"
    arm.gamerig.colors[0].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[0].normal = Color((0.4352940022945404, 0.18431399762630463, 0.4156860113143921))
    arm.gamerig.colors[0].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[0].standard_colors_lock = True
    arm.gamerig.colors[1].name = "IK"
    arm.gamerig.colors[1].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[1].normal = Color((0.6039220094680786, 0.0, 0.0))
    arm.gamerig.colors[1].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[1].standard_colors_lock = True
    arm.gamerig.colors[2].name = "Special"
    arm.gamerig.colors[2].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[2].normal = Color((0.9568629860877991, 0.7882350087165833, 0.04705899953842163))
    arm.gamerig.colors[2].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[2].standard_colors_lock = True
    arm.gamerig.colors[3].name = "Tweak"
    arm.gamerig.colors[3].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[3].normal = Color((0.03921600058674812, 0.21176500618457794, 0.5803920030593872))
    arm.gamerig.colors[3].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[3].standard_colors_lock = True
    arm.gamerig.colors[4].name = "FK"
    arm.gamerig.colors[4].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[4].normal = Color((0.11764699965715408, 0.5686269998550415, 0.035294000059366226))
    arm.gamerig.colors[4].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[4].standard_colors_lock = True
    arm.gamerig.colors[5].name = "Extra"
    arm.gamerig.colors[5].active = Color((0.5490196347236633, 1.0, 1.0))
    arm.gamerig.colors[5].normal = Color((0.9686279892921448, 0.2509799897670746, 0.09411799907684326))
    arm.gamerig.colors[5].select = Color((0.31372547149658203, 0.7843138575553894, 1.0))
    arm.gamerig.colors[5].standard_colors_lock = True

    if len(arm.collections) > 0:
        for i in arm.collections:
            arm.collections.remove(i)
    arm.collections.new("Face")
    arm.collections[-1].gamerig.row = 1
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Face (Primary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Face (Secondary)")
    arm.collections[-1].gamerig.row = 2
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Torso")
    arm.collections[-1].gamerig.row = 3
    arm.collections[-1].gamerig.group = 3
    arm.collections.new("Torso (Tweak)")
    arm.collections[-1].gamerig.row = 4
    arm.collections[-1].gamerig.group = 4
    arm.collections.new("Fingers.L")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Fingers.R")
    arm.collections[-1].gamerig.row = 5
    arm.collections[-1].gamerig.group = 6
    arm.collections.new("Arm.L (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.L (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Arm.R (IK)")
    arm.collections[-1].gamerig.row = 7
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Arm.R (FK)")
    arm.collections[-1].gamerig.row = 8
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.L (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.L (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Leg.R (IK)")
    arm.collections[-1].gamerig.row = 10
    arm.collections[-1].gamerig.group = 2
    arm.collections.new("Leg.R (FK)")
    arm.collections[-1].gamerig.row = 11
    arm.collections[-1].gamerig.group = 5
    arm.collections.new("Root")
    arm.collections[-1].gamerig.row = 14
    arm.collections[-1].gamerig.group = 1

    bones = {}

    bone = arm.edit_bones.new('hips')
    bone.head[:] = 0.0000, -0.0454, 2.0070
    bone.tail[:] = -0.0000, -0.1069, 2.4607
    bone.roll = -0.0000
    bone.use_connect = False
    bone.use_deform = True
    bones['hips'] = bone.name
    bone = arm.edit_bones.new('chest')
    bone.head[:] = -0.0000, -0.1069, 2.4607
    bone.tail[:] = -0.0000, 0.0047, 3.9491
    bone.roll = 0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['chest'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head[:] = 0.3893, -0.0099, 2.1109
    bone.tail[:] = 0.4252, -0.0652, 1.2095
    bone.roll = -0.0469
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head[:] = -0.3893, -0.0099, 2.1109
    bone.tail[:] = -0.4252, -0.0652, 1.2095
    bone.roll = 0.0469
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['hips']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head[:] = 1.0400, 0.0609, 3.5282
    bone.tail[:] = 1.2394, 0.0914, 3.0007
    bone.roll = 2.6821
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['chest']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head[:] = -1.0400, 0.0609, 3.5282
    bone.tail[:] = -1.2394, 0.0914, 3.0007
    bone.roll = -2.6821
    bone.use_connect = False
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['chest']]
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head[:] = -0.0000, 0.0047, 3.9491
    bone.tail[:] = 0.0000, 0.0038, 5.0126
    bone.roll = -0.0000
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['chest']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head[:] = 0.4252, -0.0652, 1.2095
    bone.tail[:] = 0.4566, 0.0369, 0.3583
    bone.roll = -0.0333
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head[:] = -0.4252, -0.0652, 1.2095
    bone.tail[:] = -0.4566, 0.0369, 0.3583
    bone.roll = 0.0333
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head[:] = 1.2394, 0.0914, 3.0007
    bone.tail[:] = 1.4202, 0.0367, 2.4361
    bone.roll = 2.8310
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head[:] = -1.2394, 0.0914, 3.0007
    bone.tail[:] = -1.4202, 0.0367, 2.4361
    bone.roll = -2.8310
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head[:] = 0.4566, 0.0369, 0.3583
    bone.tail[:] = 0.4600, -0.6038, 0.1243
    bone.roll = -0.0257
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head[:] = -0.4566, 0.0369, 0.3583
    bone.tail[:] = -0.4600, -0.6038, 0.1243
    bone.roll = 0.0257
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head[:] = 1.4202, 0.0367, 2.4361
    bone.tail[:] = 1.4984, 0.0433, 1.8629
    bone.roll = -1.7193
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('hand.R')
    bone.head[:] = -1.4202, 0.0367, 2.4361
    bone.tail[:] = -1.4984, 0.0433, 1.8629
    bone.roll = 1.7193
    bone.use_connect = True
    bone.use_deform = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['hand.R'] = bone.name
    bone = arm.edit_bones.new('JIG-heel.L')
    bone.head[:] = 0.1673, 0.2880, 0.0000
    bone.tail[:] = 0.7632, 0.2880, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['JIG-heel.L'] = bone.name
    bone = arm.edit_bones.new('JIG-heel.R')
    bone.head[:] = -0.1673, 0.2880, 0.0000
    bone.tail[:] = -0.7632, 0.2880, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.use_deform = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['JIG-heel.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['hips']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    try:
        pbone.gamerig.name = "torso_simple"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['chest']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.L (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.footprint_bone = "JIG-heel.L"
    except AttributeError:
        pass
    try:
        pbone.gamerig.conntact_bone = "ground.L"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    try:
        pbone.gamerig.support_ik_mode = "root"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.leg"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Leg.R (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.footprint_bone = "JIG-heel.R"
    except AttributeError:
        pass
    try:
        pbone.gamerig.conntact_bone = "ground.R"
    except AttributeError:
        pass
    try:
        pbone.gamerig.support_ik_mode = "root"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.L (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.support_ik_mode = "root"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    try:
        pbone.gamerig.name = "limbs.arm"
    except AttributeError:
        pass
    try:
        pbone.gamerig.fk_bone_collection = "Arm.R (FK)"
    except AttributeError:
        pass
    try:
        pbone.gamerig.support_ik_mode = "root"
    except AttributeError:
        pass
    try:
        pbone.gamerig.allow_ik_stretch = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Face'].assign(pbone)
    arm.collections['Torso'].assign(pbone)
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['hand.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Arm.R (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel.L']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.L (IK)'].assign(pbone)
    pbone = obj.pose.bones[bones['JIG-heel.R']]
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    arm.collections['Leg.R (IK)'].assign(pbone)

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

if __name__ == "__main__":
    create(bpy.context.active_object)
